security:
  # https://symfony.com/doc/current/security.html#where-do-users-come-from-user-providers
  encoders:
    App\Entity\Klant:
      algorithm: bcrypt
    App\Entity\Admin:
        algorithm: auto



  providers:
    app_user_provider:
      entity:
        class: App\Entity\Admin
        property: email
    # used to reload user from session & other features (e.g. switch_user)
    # used to reload user from session & other features (e.g. switch_user)

  firewalls:

    dev:
      pattern: ^/(_(profiler|wdt)|css|images|js)/
      security: false

    main:
      anonymous: lazy
      provider: app_user_provider
      guard:
          authenticators:
              - App\Security\CustomAuthAuthenticator
      logout:
          path: app_logout
          # where to redirect after logout
          # target: app_any_route

  access_control:
    - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY}
    - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
    #- { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
    #- { path: ^/api,       roles: IS_AUTHENTICATED_FULLY }