#index:
#    path: /
#    controller: App\Controller\DefaultController::index

authentication:
  path: /api/login_check
  methods: [POST]

register:
  path: /api/register
  controller: App\Controller\UserController::register
  methods: [POST, GET]

afspraak:
  path: /api/afspraak
  controller: App\Controller\AgendaController::getAgenda
  methods: [POST, GET]