#index:
#    path: /
#    controller: App\Controller\DefaultController::index

authentication:
  path: /api/login_check
  methods: [POST]

register:
  path: /api/register
  controller: App\Controller\UserController::register
  methods: [POST, GET]

agenda:
  path: /api/agenda
  controller: App\Controller\AgendaController::getAgenda
  methods: [POST, GET]

afspraak:
  path: /api/afspraak
  controller: App\Controller\AfspraakController::newAfspraak
  methods: [POST]

mijnAfspraaken:
  path: /api/mijnAfspraken
  controller: App\Controller\AfspraakController::getAfspraken
  methods: [GET]